// REPOSITORY
export const ADD_REPOSITORY = 'ADD_REPOSITORY';
export const DELETE_REPOSITORY = 'DELETE_REPOSITORY';
export const EDIT_REPOSITORY = 'EDIT_REPOSITORY';
export const RECEIVE_REPOSITORIES = 'RECEIVE_REPOSITORIES';
export const SELECT_REPOSITORY = 'SELECT_REPOSITORY';

// FILE
export const ADD_FILES = 'ADD_FILES';
export const DELETE_FILE = 'DELETE_FILE';
export const RECEIVE_FILES = 'RECEIVE_FILES';
export const SELECT_FILE = 'SELECT_FILE';
